"""Natural keys — the identifiers that cross the Central/Station boundary.

Database integer/opaque IDs never cross the sync boundary. A record is
identified by its *natural key*::

    exam_id + student_id + subject_code + paper_type [+ question_number]

Student-id handling rule (Guide §2.2):
    * IDs are supplied as-is and never generated by the system.
    * Accept ``-`` or ``/`` as separators; prefer ``-`` for new entries.
    * Never rewrite, reformat, or normalize an existing id.
    * The only enforced constraint is uniqueness within an exam (checked by
      Central, not here — this module only validates *shape*).
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from .enums import PaperType, RejectionCode
from .errors import ValidationError

# A student id is a non-empty token of alphanumerics with ``-`` or ``/`` as
# internal separators. We are deliberately permissive: field data varies. We
# reject only clearly invalid shapes (empty, whitespace, control chars).
_STUDENT_ID_RE = re.compile(r"^[A-Za-z0-9]+(?:[-/][A-Za-z0-9]+)*$")


def validate_student_id(student_id: str) -> str:
    """Validate the *shape* of a supplied student id and return it unchanged.

    Raises :class:`ValidationError` (``INVALID_STUDENT_ID``) if the shape is
    clearly invalid. Never normalizes or rewrites the id.
    """
    if not isinstance(student_id, str) or not student_id or student_id.strip() != student_id:
        raise ValidationError(
            RejectionCode.INVALID_STUDENT_ID,
            "Student id must be a non-empty string with no surrounding whitespace.",
            {"student_id": student_id},
        )
    if not _STUDENT_ID_RE.match(student_id):
        raise ValidationError(
            RejectionCode.INVALID_STUDENT_ID,
            "Student id contains invalid characters; only alphanumerics and '-' or '/' separators are allowed.",
            {"student_id": student_id},
        )
    return student_id


def prefer_hyphen_separator(student_id: str) -> str:
    """Return the id with ``/`` replaced by ``-``.

    Use this ONLY when *creating* a brand-new id from raw input where the
    system is allowed to pick the preferred separator — never on an existing id.
    """
    return student_id.replace("/", "-")


@dataclass(frozen=True, slots=True)
class NaturalKey:
    """A fully-qualified natural key for a mark/attendance record.

    ``question_number`` is present only for item-level marks.
    """

    exam_id: str
    student_id: str
    subject_code: str
    paper_type: PaperType
    question_number: str | None = None

    def to_dict(self) -> dict[str, str]:
        d: dict[str, str] = {
            "exam_id": self.exam_id,
            "student_id": self.student_id,
            "subject_code": self.subject_code,
            "paper_type": self.paper_type.value,
        }
        if self.question_number is not None:
            d["question_number"] = self.question_number
        return d

    def to_string(self) -> str:
        """A stable, human-readable flattened form (useful for logs/dedup)."""
        parts = [
            str(self.exam_id),
            self.student_id,
            self.subject_code,
            self.paper_type.value,
        ]
        if self.question_number is not None:
            parts.append(self.question_number)
        return "|".join(parts)


def build_natural_key(
    exam_id: str,
    student_id: str,
    subject_code: str,
    paper_type: PaperType | str,
    question_number: str | None = None,
) -> NaturalKey:
    """Build and validate a :class:`NaturalKey`.

    Validates that all required parts are present and non-empty, that the
    paper type is known, and that the student id has a valid shape. The student
    id is returned unchanged (never normalized).
    """
    if isinstance(paper_type, str):
        try:
            paper_type = PaperType(paper_type)
        except ValueError as exc:
            raise ValidationError(
                RejectionCode.INVALID_NATURAL_KEY,
                f"Unknown paper_type '{paper_type}'.",
                {"paper_type": paper_type},
            ) from exc

    if not isinstance(subject_code, str) or not subject_code.strip():
        raise ValidationError(
            RejectionCode.INVALID_NATURAL_KEY,
            "Natural key part 'subject_code' must be a non-empty string.",
            {"subject_code": subject_code},
        )

    validate_student_id(student_id)

    if question_number is not None:
        if not isinstance(question_number, str) or not question_number.strip():
            raise ValidationError(
                RejectionCode.INVALID_NATURAL_KEY,
                "question_number, when present, must be a non-empty string.",
                {"question_number": question_number},
            )

    return NaturalKey(
        exam_id=exam_id,
        student_id=student_id,
        subject_code=subject_code,
        paper_type=paper_type,
        question_number=question_number,
    )


def parse_natural_key(data: dict) -> NaturalKey:
    """Parse a natural key from a plain dict (e.g. a sync event payload)."""
    if not isinstance(data, dict):
        raise ValidationError(
            RejectionCode.INVALID_NATURAL_KEY,
            "Natural key must be an object.",
            {"received_type": type(data).__name__},
        )
    missing = [k for k in ("exam_id", "student_id", "subject_code", "paper_type") if k not in data]
    if missing:
        raise ValidationError(
            RejectionCode.INVALID_NATURAL_KEY,
            f"Natural key missing required field(s): {', '.join(missing)}.",
            {"missing": missing},
        )
    return build_natural_key(
        exam_id=data["exam_id"],
        student_id=data["student_id"],
        subject_code=data["subject_code"],
        paper_type=data["paper_type"],
        question_number=data.get("question_number"),
    )
