"""Versioned Pydantic contracts shared by Central and Station."""

from __future__ import annotations

from .attendance import AttendanceIn
from .collection_export import (
    CollectionManifest,
    CollectionSnapshot,
    ScopeCount,
)
from .exametrics import (
    ApprovalInstruction,
    CapabilitiesResponse,
    CollectionChunkAck,
    CollectionCounts,
    CollectionSessionComplete,
    CollectionSessionStart,
    EntitlementsResponse,
    EntitlementState,
    ErrorBody,
    ErrorEnvelope,
    ExamProvisionRequest,
    ExamProvisionResponse,
    KeyProvisionRequest,
    KeyProvisionResponse,
    ProcessingQuoteOut,
    ProcessingRequestIn,
    ProcessingRequestOut,
    ProvisionWarning,
    QuoteOut,
    RequesterInfo,
    RowValidationDetail,
    SubjectSpec,
    TenantExamInfo,
    TenantInfo,
    WebhookEnvelope,
)
from .marks import ItemMarkIn, StudentPaperMarksIn, TotalMarkIn
from .station_package import (
    CONTRACT_VERSION,
    DataEntererScopeEntry,
    MachineCredentialMeta,
    MachineCredentialPayload,
    PackageErrorCode,
    PackageFileHashes,
    PackageScope,
    SigningMeta,
    StationAdminEntry,
    StationPackageManifest,
)
from .station_sync import (
    AcceptedResult,
    DuplicateResult,
    RejectedResult,
    SyncEvent,
    SyncRequest,
    SyncResponse,
)

__all__ = [
    "AttendanceIn",
    "ItemMarkIn",
    "TotalMarkIn",
    "StudentPaperMarksIn",
    "StationPackageManifest",
    "PackageScope",
    "DataEntererScopeEntry",
    "MachineCredentialMeta",
    "MachineCredentialPayload",
    "PackageErrorCode",
    "PackageFileHashes",
    "SigningMeta",
    "StationAdminEntry",
    "CONTRACT_VERSION",
    "SyncEvent",
    "SyncRequest",
    "SyncResponse",
    "AcceptedResult",
    "DuplicateResult",
    "RejectedResult",
    "CollectionManifest",
    "CollectionSnapshot",
    "ScopeCount",
    "ApprovalInstruction",
    "CapabilitiesResponse",
    "CollectionChunkAck",
    "CollectionCounts",
    "CollectionSessionComplete",
    "CollectionSessionStart",
    "EntitlementState",
    "EntitlementsResponse",
    "ErrorBody",
    "ErrorEnvelope",
    "ExamProvisionRequest",
    "ExamProvisionResponse",
    "KeyProvisionRequest",
    "KeyProvisionResponse",
    "ProcessingQuoteOut",
    "ProcessingRequestIn",
    "ProcessingRequestOut",
    "ProvisionWarning",
    "QuoteOut",
    "RequesterInfo",
    "RowValidationDetail",
    "SubjectSpec",
    "TenantExamInfo",
    "TenantInfo",
    "WebhookEnvelope",
]
